<script src="node_modules/jquery/dist/jquery.min.js"></script>
<script src="node_modules/jquery-form/dist/jquery.form.min.js"></script>
<script src="node_modules/moment/min/moment-with-locales.min.js"></script>
<script src="node_modules/sweetalert2/dist/sweetalert2.all.min.js"></script>
<script src="node_modules/tempusdominus-bootstrap-4/build/js/tempusdominus-bootstrap-4.min.js"></script>
<script src="node_modules/summernote/dist/summernote-bs4.min.js"></script>
<script src="plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="plugins/bs-stepper/js/bs-stepper.min.js"></script>
<script src="plugins/bootstrap-switch/js/bootstrap-switch.min.js"></script>
<script src="plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
<script src="dist/js/jquery.Rut.min.js"></script>
<script src="dist/js/adminlte.js"></script>
<script src="dist/js/functions.js?<?php echo time() ?>"></script>
<script src="build/js/system.js?<?php echo time() ?>"></script>
<script src="build/js/index.js?<?php echo time() ?>"></script>